export const FACULTIES = {
    1: 'Applied Science',
    2: 'Arts',
    3: 'Science',
    4: 'Business',
    5: 'Education',
    6: 'Forestry',
    7: 'Land and Food Systems',
    8: 'Medicine',
    9: 'Other',
};

export const STANDINGS = {
    1: '1st Year',
    2: '2nd Year',
    3: '3rd Year',
    4: '4th Year and Up',
    5: 'Graduate',
    6: 'Alumni',
    7: 'Other',
};

export const UndisclosedProgramId = 76;

export const PROGRAMS = {
    1: 'Accounting',
    2: 'African Studies',
    3: 'American Studies',
    4: 'Anthropology',
    5: 'Archaeology',
    6: 'Art History',
    7: 'Asian Studies',
    8: 'Astronomy',
    9: 'Biochemistry',
    10: 'Biology',
    11: 'Biomedical Engineering',
    12: 'Business Administration',
    13: 'Canadian Studies',
    14: 'Chemistry',
    15: 'Chinese Studies',
    16: 'Civil Engineering',
    17: 'Classics',
    18: 'Cognitive Systems: Computational Intelligence and Design',
    19: 'Communication',
    20: 'Computer Science',
    21: 'Conservation and Restoration of Cultural Property',
    22: 'Criminology',
    23: 'Development Studies',
    24: 'Economics',
    25: 'Education',
    26: 'Electrical and Computer Engineering',
    27: 'English',
    28: 'Environmental Engineering',
    29: 'Environmental Sciences',
    30: 'European Studies',
    31: 'Film and Media Studies',
    32: 'Finance',
    33: 'French Studies',
    34: 'Geography',
    35: 'Germanic and Slavic Studies',
    36: 'Global Studies',
    37: 'History',
    38: 'Human Geography',
    39: 'Information Technology',
    40: 'International Business',
    41: 'International Relations',
    42: 'Italian Studies',
    43: 'Japanese Studies',
    44: 'Jewish Studies',
    45: 'Latin American Studies',
    46: 'Law',
    47: 'Linguistics',
    48: 'Management',
    49: 'Marketing',
    50: 'Mathematics',
    51: 'Mechanical Engineering',
    52: 'Media Studies',
    53: 'Microbiology',
    54: 'Middle Eastern Studies',
    55: 'Molecular Biology and Biochemistry',
    56: 'Music',
    57: 'Natural Resources Economics',
    58: 'Neuroscience',
    59: 'Nursing',
    60: 'Philosophy',
    61: 'Physics',
    62: 'Political Science',
    63: 'Psychology',
    64: 'Public Policy',
    65: 'Religious Studies',
    66: 'Romance Languages and Literatures',
    67: 'Russian and East European Studies',
    68: 'Science',
    69: 'Sociology',
    70: 'Spanish and Portuguese Studies',
    71: 'Statistics',
    72: 'Sustainability',
    73: 'Theatre',
    74: 'Urban Planning',
    75: "Women's and gender studies",
    [UndisclosedProgramId]: 'Undisclosed',
};

export const SOCIALS = {
    1: {
        name: 'GitHub',
        domain: 'github.com',
        id: 1,
    },
    2: {
        name: 'Facebook',
        domain: 'facebook.com',
        id: 2,
    },
    3: {
        name: 'Instagram',
        domain: 'instagram.com',
        id: 3,
    },
    4: {
        name: 'LinkedIn',
        domain: 'linkedin.com',
        id: 4,
    },
    5: {
        name: 'Twitter',
        domain: 'twitter.com',
        id: 5,
    },
    6: {
        name: 'Website',
        domain: null,
        id: 6,
    },
    7: {
        name: 'Figma',
        domain: 'figma.com',
        id: 7,
    },
    8: {
        name: 'Other',
        domain: null,
        id: 8,
    },
};

export const UnsetRole = 1;

export const USER_ROLES = {
    [UnsetRole]: 'Explorer',
    2: 'Admin',
    3: 'Member',
    4: 'Lead',
    5: 'Tech Leadd',
    6: 'Design Lead',
    7: 'Marketing Lead',
    8: 'Co-president',
    9: 'Developer',
    10: 'Designer',
};
