// // import { FacultyQueryResultArray } from '../getFaculties';
// // import { StandingQueryResultArray } from '../getStandings';

// export const listOfFaculties = [
//     'Forestry',
//     'Land and Food Systems',
//     'Education',
//     'Business',
//     'Arts',
//     'Applied Science',
//     'Science',
//     'Medicine',
//     'Other',
// ];

// export const facultyQueryResult: FacultyQueryResultArray[] = [
//     {
//         faculty: {
//             '1': 'Forestry',
//             '2': 'Land and Food Systems',
//             '3': 'Education',
//             '4': 'Business',
//             '5': 'Arts',
//             '6': 'Applied Science',
//             '7': 'Science',
//             '8': 'Medicine',
//             '9': 'Other',
//         },
//     },
// ];

// export const listOfStandings = [
//     '1st Year',
//     '2nd Year',
//     '3rd Year',
//     '4th Year and Up',
//     'Graduate',
//     'Alumni',
//     'Other',
// ];

// export const standingQueryResult: StandingQueryResultArray[] = [
//     {
//         standing: {
//             '1': '1st Year',
//             '2': '2nd Year',
//             '3': '3rd Year',
//             '4': '4th Year and Up',
//             '5': 'Graduate',
//             '6': 'Alumni',
//             '7': 'Other',
//         },
//     },
// ];

// export const listOfPrograms = [
//     'Accounting',
//     'African Studies',
//     'American Studies',
//     'Anthropology',
//     'Archaeology',
//     'Art History',
//     'Asian Studies',
//     'Astronomy',
//     'Biochemistry',
//     'Biology',
//     'Biomedical Engineering',
//     'Business Administration',
//     'Canadian Studies',
//     'Chemistry',
//     'Chinese Studies',
//     'Civil Engineering',
//     'Classics',
//     'Cognitive Systems: Computational Intelligence and Design',
//     'Communication',
//     'Computer Science',
//     'Conservation and Restoration of Cultural Property',
//     'Criminology',
//     'Development Studies',
//     'Economics',
//     'Education',
//     'Electrical and Computer Engineering',
//     'English',
//     'Environmental Engineering',
//     'Environmental Sciences',
//     'European Studies',
//     'Film and Media Studies',
//     'Finance',
//     'French Studies',
//     'Geography',
//     'Germanic and Slavic Studies',
//     'Global Studies',
//     'History',
//     'Human Geography',
//     'Information Technology',
//     'International Business',
//     'International Relations',
//     'Italian Studies',
//     'Japanese Studies',
//     'Jewish Studies',
//     'Latin American Studies',
//     'Law',
//     'Linguistics',
//     'Management',
//     'Marketing',
//     'Mathematics',
//     'Mechanical Engineering',
//     'Media Studies',
//     'Microbiology',
//     'Middle Eastern Studies',
//     'Molecular Biology and Biochemistry',
//     'Music',
//     'Natural Resources Economics',
//     'Neuroscience',
//     'Nursing',
//     'Philosophy',
//     'Physics',
//     'Political Science',
//     'Psychology',
//     'Public Policy',
//     'Religious Studies',
//     'Romance Languages and Literatures',
//     'Russian and East European Studies',
//     'Science',
//     'Sociology',
//     'Spanish and Portuguese Studies',
//     'Statistics',
//     'Sustainability',
//     'Theatre',
//     'Urban Planning',
//     "Women's and gender studies",
// ];

// export const programQueryResult = [
//     {
//         program: {
//             '1': 'Accounting',
//             '2': 'African Studies',
//             '3': 'American Studies',
//             '4': 'Anthropology',
//             '5': 'Archaeology',
//             '6': 'Art History',
//             '7': 'Asian Studies',
//             '8': 'Astronomy',
//             '9': 'Biochemistry',
//             '10': 'Biology',
//             '11': 'Biomedical Engineering',
//             '12': 'Business Administration',
//             '13': 'Canadian Studies',
//             '14': 'Chemistry',
//             '15': 'Chinese Studies',
//             '16': 'Civil Engineering',
//             '17': 'Classics',
//             '18': 'Cognitive Systems: Computational Intelligence and Design',
//             '19': 'Communication',
//             '20': 'Computer Science',
//             '21': 'Conservation and Restoration of Cultural Property',
//             '22': 'Criminology',
//             '23': 'Development Studies',
//             '24': 'Economics',
//             '25': 'Education',
//             '26': 'Electrical and Computer Engineering',
//             '27': 'English',
//             '28': 'Environmental Engineering',
//             '29': 'Environmental Sciences',
//             '30': 'European Studies',
//             '31': 'Film and Media Studies',
//             '32': 'Finance',
//             '33': 'French Studies',
//             '34': 'Geography',
//             '35': 'Germanic and Slavic Studies',
//             '36': 'Global Studies',
//             '37': 'History',
//             '38': 'Human Geography',
//             '39': 'Information Technology',
//             '40': 'International Business',
//             '41': 'International Relations',
//             '42': 'Italian Studies',
//             '43': 'Japanese Studies',
//             '44': 'Jewish Studies',
//             '45': 'Latin American Studies',
//             '46': 'Law',
//             '47': 'Linguistics',
//             '48': 'Management',
//             '49': 'Marketing',
//             '50': 'Mathematics',
//             '51': 'Mechanical Engineering',
//             '52': 'Media Studies',
//             '53': 'Microbiology',
//             '54': 'Middle Eastern Studies',
//             '55': 'Molecular Biology and Biochemistry',
//             '56': 'Music',

//             '57': 'Natural Resources Economics',
//             '58': 'Neuroscience',
//             '59': 'Nursing',
//             '60': 'Philosophy',
//             '61': 'Physics',
//             '62': 'Political Science',
//             '63': 'Psychology',
//             '64': 'Public Policy',
//             '65': 'Religious Studies',
//             '66': 'Romance Languages and Literatures',
//             '67': 'Russian and East European Studies',
//             '68': 'Science',
//             '69': 'Sociology',
//             '70': 'Spanish and Portuguese Studies',
//             '71': 'Statistics',
//             '72': 'Sustainability',
//             '73': 'Theatre',
//             '74': 'Urban Planning',
//             '75': "Women's and gender studies",
//         },
//     },
// ];

// export const listOfSocials = [
//     {
//         name: 'GitHub',
//         domain: 'github.com',
//     },
//     {
//         name: 'Facebook',
//         domain: 'facebook.com',
//     },
//     {
//         name: 'Instagram',
//         domain: 'instagram.com',
//     },
//     {
//         name: 'LinkedIn',
//         domain: 'linkedin.com',
//     },
//     {
//         name: 'Twitter',
//         domain: 'twitter.com',
//     },
//     {
//         name: 'Website',
//         domain: null,
//     },
//     {
//         name: 'Figma',

//         domain: 'figma.com',
//     },
//     {
//         name: 'Other',
//         domain: null,
//     },
// ];

// export const socialQueryResult = [
//     {
//         socials: {
//             '1': {
//                 name: 'GitHub',
//                 domain: 'github.com',
//                 id: 1,
//             },
//             '2': {
//                 name: 'Facebook',
//                 domain: 'facebook.com',
//                 id: 2,
//             },
//             '3': {
//                 name: 'Instagram',
//                 domain: 'instagram.com',
//                 id: 3,
//             },
//             '4': {
//                 name: 'LinkedIn',
//                 domain: 'linkedin.com',
//                 id: 4,
//             },
//             '5': {
//                 name: 'Twitter',
//                 domain: 'twitter.com',
//                 id: 5,
//             },
//             '6': {
//                 name: 'Website',
//                 domain: null,
//                 id: 6,
//             },
//             '7': {
//                 name: 'Figma',
//                 domain: 'figma.com',
//                 id: 7,
//             },
//             '8': {
//                 name: 'Other',
//                 domain: null,
//                 id: 8,
//             },
//         },
//     },
// ];
