ALTER TABLE person 
    ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


UPDATE person
    SET created_at  = CURRENT_TIMESTAMP;

ALTER TABLE person
    ADD COLUMN member_since TIMESTAMP DEFAULT NULL;


