INSERT INTO faculty (label) VALUES
('Forestry'),
('Land and Food Systems'),
('Education'),
('Business'),
('Arts'),
('Applied Science'),
('Science'),
('Medicine'),
('Other');


INSERT INTO standing (label) VALUES 
('First Year'),
('Second Year'),
('Third Year'),
('Fourth Year and up'),
('Graduate Student'),
('Alumni'),
('Other');

INSERT INTO role (id, label) VALUES
(1, 'Explorer');;



-- Populate degree_program table
INSERT INTO specialization (label)
VALUES
  ('Accounting'),
  ('African Studies'),
  ('American Studies'),
  ('Anthropology'),
  ('Archaeology'),
  ('Art History'),
  ('Asian Studies'),
  ('Astronomy'),
  ('Biochemistry'),
  ('Biology'),
  ('Biomedical Engineering'),
  ('Business Administration'),
  ('Canadian Studies'),
  ('Chemistry'),
  ('Chinese Studies'),
  ('Civil Engineering'),
  ('Classics'),
  ('Cognitive Systems: Computational Intelligence and Design'),
  ('Communication'),
  ('Computer Science'),
  ('Conservation and Restoration of Cultural Property'),
  ('Criminology'),
  ('Development Studies'),
  ('Economics'),
  ('Education'),
  ('Electrical and Computer Engineering'),
  ('English'),
  ('Environmental Engineering'),
  ('Environmental Sciences'),
  ('European Studies'),
  ('Film and Media Studies'),
  ('Finance'),
  ('French Studies'),
  ('Geography'),
  ('Germanic and Slavic Studies'),
  ('Global Studies'),
  ('History'),
  ('Human Geography'),
  ('Information Technology'),
  ('International Business'),
  ('International Relations'),
  ('Italian Studies'),
  ('Japanese Studies'),
  ('Jewish Studies'),
  ('Latin American Studies'),
  ('Law'),
  ('Linguistics'),
  ('Management'),
  ('Marketing'),
  ('Mathematics'),
  ('Mechanical Engineering'),
  ('Media Studies'),
  ('Microbiology'),
  ('Middle Eastern Studies'),
  ('Molecular Biology and Biochemistry'),
  ('Music'),
  ('Natural Resources Economics'),
  ('Neuroscience'),
  ('Nursing'),
  ('Philosophy'),
  ('Physics'),
  ('Political Science'),
  ('Psychology'),
  ('Public Policy'),
  ('Religious Studies'),
  ('Romance Languages and Literatures'),
  ('Russian and East European Studies'),
  ('Science'),
  ('Sociology'),
  ('Spanish and Portuguese Studies'),
  ('Statistics'),
  ('Sustainability'),
  ('Theatre'),
  ('Urban Planning'),
  ('Other');