-- Create Area table
CREATE TABLE IF NOT EXISTS area (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    parent_areaid INT DEFAULT NULL,
    FOREIGN KEY (parent_areaid) REFERENCES area(id) ON DELETE NO ACTION
);

-- Create Documents table
CREATE TABLE IF NOT EXISTS document (
    id SERIAL PRIMARY KEY,
    areaid INT NOT NULL,
    title VARCHAR(500) NOT NULL,
    fileid VARCHAR(500) NOT NULL UNIQUE,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (areaid) REFERENCES area(id) ON DELETE CASCADE
);
